version: '3.8'

services:
  backend:
    build:
      context: ./backend/user-register
    container_name: backend
    ports:
      - "9090:9090"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/user-register
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
